apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: default
  labels:
    app: kibana
    heritage: Helm
    release: kibana
  name: kibana-kibana
  namespace: default
spec:
  #clusterIP: 10.103.246.12
  #clusterIPs:
  #- 10.103.246.12
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kibana
  sessionAffinity: None
  type: ClusterIP
#status:
  #loadBalancer: {}
  type: LoadBalancer
