apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-kibana
  namespace: default
spec:
  #clusterIP: 10.103.246.12
  #clusterIPs:
  #- 10.103.246.12
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
#status:
  #loadBalancer: {}
  type: LoadBalancer
