apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash-logstash
    chart: logstash
    release: logstash
  name: logstash-logstash-headless
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: logstash-logstash
  sessionAffinity: None
  type: LoadBalancer
